language: node_js
node_js:
- 4.4.0
env:
  global:
  - NODE_ENV=test
branches:
  only:
  - master
sudo: true
install:
- npm install
cache:
  directories:
    - node_modules
services:
- mongodb
- redis-server
before_script:
- sleep 10
script:
- npm test
