language: node_js
node_js:
- 4.4.0
- 6.0.0
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - gcc-4.8
    - g++-4.8
env:
  global:
  - NODE_ENV=test CXX=g++-4.8
branches:
  only:
  - master
sudo: true
install:
- npm install
cache:
  directories:
    - node_modules
services:
- mongodb
- redis-server
before_script:
- sleep 10
script:
- npm test
